/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busbookingsystem2;

import static java.awt.Event.DELETE;
import java.sql.Statement;
import java.sql.ResultSet;

import java.awt.Toolkit;
import static java.awt.event.PaintEvent.UPDATE;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import static java.sql.DriverManager.getConnection;
import static java.sql.DriverManager.getConnection;
import static java.sql.DriverManager.getConnection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.value;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author HP
 */
public class editdetails extends javax.swing.JFrame {

    /**
     * Creates new form editdetails
     */
    public editdetails() {
        initComponents();
        show_buses_In_JTable();
    }
    public Connection getConnection()
    {
        Connection con;
        try{
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/busdata","busdataa","naum");
            return con;
        } catch(Exception e){
            e.printStackTrace();
            return null;
    }
    }
    
   public ArrayList<User>getUsersList()
   {
       ArrayList<User>usersList=new ArrayList<User>();
       Connection connection = getConnection();
       String query = "SELECT * FROM BUSDATAA.BUSDATA ";
       Statement st;
       ResultSet rs;
       
       try{
           st =connection.createStatement();
           rs = st.executeQuery(query);
           User user;
           while(rs.next())
           {
               user = new User(rs.getString("BUSCODE"),rs.getString("FROMCITY"),rs.getString("TOCITY"),rs.getString("SERVICE"),rs.getInt("COST"),rs.getInt("RSEATS"),rs.getString("DATE"),rs.getString("TIME"));
               usersList.add(user);
           }
               
       
     }
       catch (Exception e){
           e.printStackTrace();
       }
       return usersList;
   }
    public void show_buses_In_JTable()
    {
        ArrayList<User> list =getUsersList();
        DefaultTableModel model=(DefaultTableModel)jTabledata .getModel();
        Object[] row = new Object[8];
        for (int i =0;i<list.size();i++)
        {
            
            row[0]=list.get(i).getBus_code();
            row[1]=list.get(i).getfrom();
            row[2]=list.get(i).getto();
            row[3]=list.get(i).getservice();
            row[4]=list.get(i).getcost();
            row[5]=list.get(i).getDate();
            row[6]=list.get(i).getTime();
            row[7]=list.get(i).getR_seats();
            model.addRow(row);
           
             
            
        }
    }
     public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
              
               DefaultTableModel model = (DefaultTableModel)jTabledata.getModel();
               model.setRowCount(0);
               show_buses_In_JTable();
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }
    
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jfrom = new javax.swing.JTextField();
        jTo = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jservice = new javax.swing.JTextField();
        jcost = new javax.swing.JTextField();
        jtime = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledata = new javax.swing.JTable();
        dare = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rseatss = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 500, 600));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true), "Update data", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Bus code");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("From");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("To");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Service");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Cost");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Time");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anuradhapura", "Ampara", "Colombo", "Kandy", "Kurunegala", "Galle", "Jaffna", "Trincomalee", "Mannar", "NuwaraEliya" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anuradhapura", "Ampara", "Colombo", "Kandy", "Kurunegala", "Galle", "Jaffna", "Trincomalee", "Mannar", "NuwaraEliya" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        jfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfromActionPerformed(evt);
            }
        });
        jPanel1.add(jfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 121, -1));
        jPanel1.add(jTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 121, -1));
        jPanel1.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 147, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semi luxury", "Luxury" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 94, -1));
        jPanel1.add(jservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 121, -1));
        jPanel1.add(jcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, -1));
        jPanel1.add(jtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 121, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5.00AM", "8.00AM", "10.15AM", "12.30PM", "3.30PM", "6.00PM", "9.00PM" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 67, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Insert");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Update DB");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 130, -1));

        jTabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BusCode", "From", "To", "Service", "Cost", "Date", "Time", "R_seats"
            }
        ));
        jTabledata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabledataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabledata);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 610, 170));
        jPanel1.add(dare, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("RSeats");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        jPanel1.add(rseatss, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 500));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 100, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 120, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       String selectedValue = jComboBox1.getSelectedItem().toString();
       
       jfrom.setText(selectedValue);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfromActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
private JFrame frame;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Bus booking systems",
              JOptionPane.YES_NO_OPTION  )== JOptionPane.YES_NO_OPTION){
            System.exit(0);
    }                    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
      String selectedValue = jComboBox2.getSelectedItem().toString();
       
       jTo.setText(selectedValue);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
   String selectedValue = jComboBox3.getSelectedItem().toString();
       
       jservice.setText(selectedValue);
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
    String selectedValue = jComboBox4.getSelectedItem().toString();
       
       jtime.setText(selectedValue);
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.hide();
        Welcome info =new Welcome();
        info.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTabledataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabledataMouseClicked
         int i = jTabledata.getSelectedRow();

        TableModel model = jTabledata.getModel();
       code.setText(model.getValueAt(i,0).toString());
       jcost.setText(model.getValueAt(i,4).toString());
       //jDate.setDate(model.getValueAt(i,0).toString());
       jfrom.setText(model.getValueAt(i,1).toString());
       jTo.setText(model.getValueAt(i,2).toString());
       jservice.setText(model.getValueAt(i,3).toString());
       //code.setText(model.getValueAt(i,0).toString());
       dare.setText(model.getValueAt(i, 5).toString());
       jtime.setText(model.getValueAt(i, 6).toString());
       rseatss.setText(model.getValueAt(i, 7).toString());
   
    }//GEN-LAST:event_jTabledataMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTabledata.getModel();
       model.addRow(new Object[]{
           code.getText(),
           jfrom.getText(),
           jTo.getText(),
           jservice.getText(),
           jcost.getText(),
           dare.getText(),
           jtime.getText(),
           rseatss.getText(),
          
          
       });
    }//GEN-LAST:event_jButton5ActionPerformed
//' " +jcost.getText()+"'
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     int rows = jTabledata.getRowCount();

System.out.println(""+rows);
for(int row = 0; row<rows ; row++)
{

String BUSCODE = (String)  jTabledata.getValueAt(row, 0);
String FROMCITY = (String)  jTabledata.getValueAt(row, 1);
String TOCITY = (String)  jTabledata.getValueAt(row, 2);
String SERVICE = (String)  jTabledata.getValueAt(row, 3);
String COST = (String)  jTabledata.getValueAt(row, 4);
String DATE = (String)  jTabledata.getValueAt(row, 5);
String TIME = (String)  jTabledata.getValueAt(row, 6);
String RSEATS = (String)  jTabledata.getValueAt(row, 7);



  

  //String pass = (String)  jTabledata.getValueAt(row, 3);
 try{
  Class.forName("org.apache.derby.jdbc.ClientDriver");
    java.sql.Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/busdata","busdataa","naum");


  String query = "insert into BUSDATA(BUSCODE,FROMCITY,TOCITY,SERVICE,COST,DATE,TIME,RSEATS) values("+code.getText()+","+jfrom.getText()+","+jTo.getText()+","+jservice.getText()+","+jcost.getText()+","+dare.getText()+","+jtime.getText()+","+jfrom.getText()+")" ;


 PreparedStatement stmt = con.prepareStatement(query);
 stmt.setString(0,BUSCODE); 
 stmt.setString(1, FROMCITY); 
 stmt.setString(2,TOCITY); 
 stmt.setString(3,SERVICE); 
 stmt.setString(4,COST); 
 stmt.setString(5, DATE); 
 stmt.setString(6,TIME); 
 stmt.setString(7,RSEATS); 


 stmt.addBatch();
stmt.executeBatch();
 con.commit();
 }

 catch(Exception ex)
 {
  JOptionPane.showMessageDialog(null, "Cannot save. "+ ex);
    }    
}

set();
        
         
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model =(DefaultTableModel)jTabledata.getModel();
        if (jTabledata.getSelectedRow()==-1){
            if(jTabledata.getRowCount()==0){
                
                
                JOptionPane.showMessageDialog(null, "No data to delete",
                        
                        "Bus booking system",JOptionPane.OK_OPTION);
            }else{
                
                JOptionPane.showMessageDialog(null, "Select a row to delete",
                        "Bus booking system",JOptionPane.OK_OPTION);
            }
        }else{
            
            model.removeRow(jTabledata.getSelectedRow());
            
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JTextField dare;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabledata;
    private javax.swing.JTextField jTo;
    private javax.swing.JTextField jcost;
    private javax.swing.JTextField jfrom;
    private javax.swing.JTextField jservice;
    private javax.swing.JTextField jtime;
    private javax.swing.JTextField rseatss;
    // End of variables declaration//GEN-END:variables

    private void Show_Users_In_JTable() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void set() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
