
package busbookingsystem2;

import java.sql.Statement;
import java.sql.ResultSet;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import static java.sql.DriverManager.getConnection;
import static java.sql.DriverManager.getConnection;
import static java.sql.DriverManager.getConnection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class findyour2 extends javax.swing.JFrame {

    /**
     * Creates new form findyour2
     */
    public findyour2() {
        initComponents();
        show_buses_In_JTable();
    }
    DefaultTableModel dm;
    
    
     public Connection getConnection()
    {
        Connection con;
        try{
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/busdata","busdataa","naum");
            return con;
        } catch(Exception e){
            e.printStackTrace();
            return null;
    }
    }
     public ArrayList<User>getUsersList()
   {
       ArrayList<User>usersList=new ArrayList<User>();
       Connection connection = getConnection();
       String query = "SELECT * FROM BUSDATAA.BUSDATA ";
       Statement st;
       ResultSet rs;
       
       try{
           st =connection.createStatement();
           rs = st.executeQuery(query);
           User user;
           while(rs.next())
           {
               user = new User(rs.getString("BUSCODE"),rs.getString("FROMCITY"),rs.getString("TOCITY"),rs.getString("SERVICE"),rs.getInt("COST"),rs.getInt("RSEATS"),rs.getString("DATE"),rs.getString("TIME"));
               usersList.add(user);
           }
               
       
     }
       catch (Exception e){
           e.printStackTrace();
       }
       return usersList;
   }
     public void show_buses_In_JTable()
    {
        ArrayList<User> list =getUsersList();
        DefaultTableModel model=(DefaultTableModel)jTabledata2 .getModel();
        Object[] row = new Object[9];
        for (int i =0;i<list.size();i++)
        {
            
            row[0]=list.get(i).getBus_code();
            row[1]=list.get(i).getfrom();
            row[2]=list.get(i).getto();
            row[3]=list.get(i).getservice();
            row[4]=list.get(i).getcost();
            row[5]=list.get(i).getDate();
            row[6]=list.get(i).getTime();
            row[7]=list.get(i).getR_seats();
            
            model.addRow(row);
           
             
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledata2 = new javax.swing.JTable();
        jTextField_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_code3 = new javax.swing.JTextField();
        jTextField_from3 = new javax.swing.JTextField();
        jTextField_to3 = new javax.swing.JTextField();
        jTextField_service3 = new javax.swing.JTextField();
        jTextField_cost3 = new javax.swing.JTextField();
        jTextField_date3 = new javax.swing.JTextField();
        jTextField_time3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_seat = new javax.swing.JTextField();
        jTextField_total = new javax.swing.JTextField();
        jComboBox_seat = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton_print = new javax.swing.JButton();
        jButton_generate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton_back1 = new javax.swing.JButton();
        jButton_exit3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Find your bus code", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter your National ID");

        jTabledata2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus Code", "From", "To", "Service", "Cost(LKR)", "Date", "Time", "R seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabledata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabledata2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabledata2);

        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });
        jTextField_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_idKeyReleased(evt);
            }
        });

        jLabel2.setText("Bus code");

        jLabel3.setText("From");

        jLabel4.setText("To");

        jLabel5.setText("Service");

        jLabel6.setText("Cost per seat(LKR)");

        jLabel7.setText("Date");

        jLabel8.setText("Time");

        jTextField_date3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_date3ActionPerformed(evt);
            }
        });

        jLabel9.setText("No of seats");

        jTextField_seat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_seatMouseClicked(evt);
            }
        });
        jTextField_seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_seatActionPerformed(evt);
            }
        });

        jComboBox_seat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox_seat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_seatMouseClicked(evt);
            }
        });
        jComboBox_seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_seatActionPerformed(evt);
            }
        });

        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        jButton_print.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_print.setText("Print ticket");
        jButton_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_printActionPerformed(evt);
            }
        });

        jButton_generate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_generate.setText("Generate ticket");
        jButton_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_generateActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total cost(LKR)");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Finish");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("NOTE: TABLE HERE SHOWS THE BUS SERVICES AVAILABLE FOR NEXT 30 DAYS ONLY");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("SELECT FROM THE TABLE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_to3)
                            .addComponent(jTextField_from3)
                            .addComponent(jTextField_code3)
                            .addComponent(jTextField_service3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jTextField_cost3)
                            .addComponent(jTextField_date3)
                            .addComponent(jTextField_time3))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(83, 83, 83)
                                    .addComponent(jTextField_total, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_seat, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox_seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(113, 113, 113)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_generate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jButton_print, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_code3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_from3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_to3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField_service3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField_cost3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField_date3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField_time3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton_generate)
                        .addGap(58, 58, 58)
                        .addComponent(jButton_print)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jButton3))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jButton_back1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_back1.setText("Back");
        jButton_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_back1ActionPerformed(evt);
            }
        });

        jButton_exit3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_exit3.setText("Exit");
        jButton_exit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exit3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_back1)
                    .addComponent(jButton_exit3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_back1ActionPerformed
     this.hide();
        Welcome info =new Welcome();
        info.setVisible(true);
    }//GEN-LAST:event_jButton_back1ActionPerformed

    private void jButton_exit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exit3ActionPerformed
      JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Bus booking systems",
              JOptionPane.YES_NO_OPTION  )== JOptionPane.YES_NO_OPTION){
            System.exit(0);
    }        
    }//GEN-LAST:event_jButton_exit3ActionPerformed

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        DefaultTableModel table=(DefaultTableModel)jTabledata2.getModel();
        String search =jTextField_id.getText().toLowerCase();
        TableRowSorter<DefaultTableModel>tr = new TableRowSorter<DefaultTableModel>(table);
        jTabledata2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
        
        
    }//GEN-LAST:event_jTextField_idActionPerformed
    
    private void jTextField_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idKeyReleased
        
    }//GEN-LAST:event_jTextField_idKeyReleased
    private void filter(String query)
    {
         dm=(DefaultTableModel)jTabledata2.getModel();
         TableRowSorter<DefaultTableModel>tr = new TableRowSorter<DefaultTableModel>(dm);
         jTabledata2.setRowSorter(tr);
         tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    private void jTabledata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabledata2MouseClicked
    
        DefaultTableModel model=(DefaultTableModel)jTabledata2.getModel();
        int selectedRowIndex=jTabledata2.getSelectedRow();
        
        jTextField_code3.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jTextField_from3.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jTextField_to3.setText(model.getValueAt(selectedRowIndex, 2).toString());
        jTextField_service3.setText(model.getValueAt(selectedRowIndex, 3).toString());
        jTextField_cost3.setText(model.getValueAt(selectedRowIndex, 4).toString());
        jTextField_date3.setText(model.getValueAt(selectedRowIndex, 5).toString());
        jTextField_time3.setText(model.getValueAt(selectedRowIndex, 6).toString());
        
        
        
        /*   int index = jTabledata2.getSelectedRow();
       TableModel model = jTabledata2.getModel();
       String bus_code = model.getValueAt(index, 0).toString();
       String from = model.getValueAt(index, 1).toString();
       String to = model.getValueAt(index, 2).toString();
       String service = model.getValueAt(index, 3).toString();
       String cost = model.getValueAt(index, 4).toString();
       String date= model.getValueAt(index, 5).toString();
       String time= model.getValueAt(index, 6).toString();
       String Rseats = model.getValueAt(index, 7).toString();
       
       jtRowData.setVisible(true);
       jtRowData.pack();
       jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
       jtRowData.jTextField_code1.setText(bus_code);
       jtRowData.jTextField_from2.setText(from);
       jtRowData.jTextField_to2.setText(to);
       jtRowData.jTextField_code1.setText(service);
       jtRowData.jTextFidel\;*/
       
    }//GEN-LAST:event_jTabledata2MouseClicked

    private void jTextField_date3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_date3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_date3ActionPerformed

    private void jComboBox_seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_seatActionPerformed
       String selectedValue = jComboBox_seat.getSelectedItem().toString();
       
    jTextField_seat.setText(selectedValue);
    int a,b,c;
       a=Integer.parseInt(jTextField_cost3.getText());
       b=Integer.parseInt(jTextField_seat.getText());
       c=a*b;
       jTextField_total.setText(""+c);
    }//GEN-LAST:event_jComboBox_seatActionPerformed

    private void jButton_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_generateActionPerformed
       area.setText("**************************************\n");
       area.setText(area.getText()+"  Camel bus booking service  \n");
       area.setText(area.getText()+"**************************************\n");
       
       
       
       area.setText(area.getText()+"ID number:"+jTextField_id.getText()+"\n");
       area.setText(area.getText()+"Buscode:"+jTextField_code3.getText()+"\n");
       area.setText(area.getText()+"Date:"+jTextField_date3.getText()+"\n");
       area.setText(area.getText()+"From:"+jTextField_from3.getText()+"\n");
       area.setText(area.getText()+"To:"+jTextField_to3.getText()+"\n");
       area.setText(area.getText()+"Service:"+jTextField_service3.getText()+"\n");
       area.setText(area.getText()+"Number of seats:"+jTextField_seat.getText()+"\n");
       area.setText(area.getText()+"Total:"+jTextField_total.getText()+"\n");
       area.setText(area.getText()+" ********* THANK YOU*********  \n");
       
       
    }//GEN-LAST:event_jButton_generateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jTextField_code3.setText("");
       jTextField_date3.setText("");
       jTextField_from3.setText("");
       jTextField_to3.setText("");
       jTextField_service3.setText("");
       jTextField_total.setText("");
       area.setText("");
       jTextField_cost3.setText("");
       jTextField_time3.setText("");
       jTextField_seat.setText("");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_seatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_seatActionPerformed

    private void jTextField_seatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_seatMouseClicked
       
    }//GEN-LAST:event_jTextField_seatMouseClicked

    private void jComboBox_seatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_seatMouseClicked
        int a,b,c;
       a=Integer.parseInt(jTextField_cost3.getText());
       b=Integer.parseInt(jTextField_seat.getText());
       c=a*b;
       jTextField_total.setText(""+c);
    }//GEN-LAST:event_jComboBox_seatMouseClicked

    private void jButton_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_printActionPerformed
       try{
           area.print();
       }
       catch(Exception e)
       {
           
       }
    }//GEN-LAST:event_jButton_printActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
        Last info =new Last();
        info.setVisible(true);       
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(findyour2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(findyour2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(findyour2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(findyour2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new findyour2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_back1;
    private javax.swing.JButton jButton_exit3;
    private javax.swing.JButton jButton_generate;
    private javax.swing.JButton jButton_print;
    private javax.swing.JComboBox<String> jComboBox_seat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabledata2;
    private javax.swing.JTextField jTextField_code3;
    private javax.swing.JTextField jTextField_cost3;
    private javax.swing.JTextField jTextField_date3;
    private javax.swing.JTextField jTextField_from3;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_seat;
    private javax.swing.JTextField jTextField_service3;
    private javax.swing.JTextField jTextField_time3;
    private javax.swing.JTextField jTextField_to3;
    private javax.swing.JTextField jTextField_total;
    // End of variables declaration//GEN-END:variables
}
